config/routes.rb
Rails.application.routes.draw do
    root to:"pages#home"
    get 'about', to: 'pages#about'
    get 'developers', to: 'pages#developers'
    get 'investors', to: 'pages#investors'
    resources :contacts, only: [:create, :new]
    get 'contact-us', to: 'contacts#new'
end
    

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
    validates :comments, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(contacts_params)
        if @contact.save
            name = params[:contacts][:name]
            email = params[:contacts][:email]
            body = params[:contacts][:comments]
            ContactMailer.contact_email(name, email, body).deliver
            flash[:success] = "Your message has been successfully delivered!"
            redirect_to root_path
        else
            flash[:danger] = @contact.errors.full_messages.join(",  ")
            redirect_to root_path
        end
    end
    
    private

    def contacts_params
        params.require(:contacts).permit(:name, :email, :comments)
    end    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def about
    end
    
    def developers
    end
    
    def investors
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
    <div class="row">
        <h3 class="text-center">Contact Us</h3>
            <div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-8 col-xs-offset-2" >
                <div class="well">
                    <%= form_for @contact do |f| %>
                        
                        <div class="form-group">
                            <%= f.label :name %>
                            <%= f.text_field :name, class: 'form-control' %>
                        </div>
                            
                        <div class="form-group">
                            <%= f.label :email %>
                            <%= f.text_field :email, class: 'form-control' %>
                        </div>    
                                
                        <div class="form-group">    
                            <%= f.label :comments %>
                            <%= f.text_area :comments, class: 'form-control' %>
                        </div>
                    
                        <%= f.submit 'Submit', class: 'btn btn-default' %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevMatch</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Montserrat:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fas fa-fire"></i>
            DevMatch
          <% end %>  
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Investors", investors_path %></li>
            <li><%= link_to "Developers", developers_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
<%= yield %>
    </div>
    <div class="container">
      <div class="row">
          <h3 class="text-center">Contact Us</h3>
            <% flash.each do |type, msg| %>
            <%= content_tag :div, msg, class: "alert alert-#{type}" %>
            <% end %>
              <div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-8 col-xs-offset-2" >
                  <div class="well">
                    <%= flash[:error] %>
                      <form class="new_contact" id="new_contact" action="/contacts" accept-charset="UTF-8" method="post">
                        <%= form_for :contacts do |f| %>
                      
                            <div class="form-group">
                                <%= f.label :name %>
                                <%= f.text_field :name, class: 'form-control' %>
                            </div>
                                
                            <div class="form-group">
                                <%= f.label :email %>
                                <%= f.text_field :email, class: 'form-control' %>
                            </div>    
                                    
                            <div class="form-group">    
                                <%= f.label :comments %>
                                <%= f.text_area :comments, class: 'form-control' %>
                            </div>
                        
                            <%= f.submit 'Submit', class: 'btn btn-default' %>
                        <% end %>
                      </form>
                    </div>  
                </div>
            </div>
        </div>
  </body>
</html>

app/views/pages/about.html.erb
<body class="home-callout">
    <div class="container text-left-indent"> 
        <h1>It's an about page</h1>
    </div>
    
    <div class="container text-center"> 
        <h3>At DevMatch we create connections between developers and investors, 
        giving them the opportunity to create meaningful advances in the development 
        of today's technology</h3>
    </div>

</body>

app/views/pages/developers.html.erb
<body class="home-callout">
    <div class="container text-left-indent">
        <h1>Devolping Something World Changing!</h1>
    </div>
    
    <div class="container text-center">
        <h3>You've worked hard to create something meaningful, now it's time to 
        bring it to the world. Our Developers are passionate about what they do.
        That's why being a DevMatch member is so valuable. Bringing your work to
        the community is what our Investors do.</h3>
    </div>
    <br><br><br><br><br>
    <div class="container text-right">
        <p>Learn about Developers here!</p>
    </div>
</body>

app/views/pages/home.html.erb
<body class="home-callout">
    <div class="text-center container-fluid">
        <h1>Welcome to DevMatch!</h1>
        <h3>A membership site where Investors and Developers get together</h3>
     </div>
</body>
 

app/views/pages/investors.html.erb
<body class="home-callout">
    <div class="container text-left-indent">
        <h1>Invest in Making a Difference!</h1>
    </div>
    
    <div class="container text-center">
        <h3>At DevMatch we help all types of investors. Our goal is to not only
        allow you to find investment opportunities that will be profitable, 
        but will bring you the opportunity to make an impact in areas you care 
        about as well.</h3>
    </div>
    <br><br><br><br><br>
    <div class="container text-right">
        <p>Learn about Investors here!</p>
    </div>
</body>